name: deploy_github_pages

on:
  push:
    branches: ["docs"] # Ensure this matches your docs branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy_site:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v4

      - name: upload_pages_artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This should point to the folder containing your index.html
          path: "docs"

      - name: deploy_to_pages
        id: deployment
        uses: actions/deploy-pages@v4
