name: deploy_github_pages

on:
  push:
    branches: ["main"] # Change this to "docs" or your default branch name

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy_site:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v4

      - name: upload_pages_artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # If your prebuilt HTML is inside the 'docs' folder, use "docs"
          # If it is in the root of the repo, use "."
          path: "docs"

      - name: deploy_to_pages
        uses: actions/deploy-pages@v4
