name: deploy_github_pages

on:
  push:
    branches: ["main"]
  # This line allows you to trigger a fresh run manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# This ensures only one deployment happens at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy_site:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v4

      - name: upload_pages_artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Your files are here. This makes 'docs' the root of your site.
          path: "docs"

      - name: deploy_to_pages
        id: deployment
        uses: actions/deploy-pages@v4
